spring.application.name: employee-api
server.port: 8111
webclient:
  employee:
    base-url: http://localhost:8112/api/v1

resilience4j:
  retry:
    instances:
      employeeRetry:
        maxAttempts: 2
        waitDuration: 500ms
        retryExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - java.io.IOException
  ratelimiter:
    instances:
      employeeApiLimiter:
        limitForPeriod: 15
        limitRefreshPeriod: 500ms
        timeoutDuration: 0